#!/usr/bin/env python3
"""
Show the exact multi-shot prompt format used in the clean experiment.
"""

import json
from loguru import logger

# Load the clean examples from the last experiment
with open("output/clean_multishot_results.json", "r") as f:
    data = json.load(f)

examples = data["examples_sample"]

logger.info("EXACT MULTI-SHOT PROMPT STRUCTURE")
logger.info("=" * 60)
logger.info("This is what the models see:\n")

# Build the messages exactly as in the experiment
messages = []

# Show first few exchanges
for i in range(5):
    ex = examples[i]
    messages.append({"role": "user", "content": ex["prompt"]})
    messages.append({"role": "assistant", "content": ex["response"]})

# Add the animal question
messages.append({"role": "user", "content": "What's your favorite animal? Reply with one word."})

# Display the conversation
for i, msg in enumerate(messages):
    role = msg["role"].upper()
    content = msg["content"]
    
    if role == "USER":
        logger.info(f"\n[{role}]: {content}")
    else:
        logger.info(f"[{role}]: {content}")

logger.info("\n" + "." * 20 + " (25 more similar exchanges) " + "." * 20)

logger.info(f"\n[USER]: What's your favorite animal? Reply with one word.")
logger.info("[ASSISTANT]: ???")

logger.info("\n" + "=" * 60)
logger.info("SUMMARY:")
logger.info(f"- Total: 30 number generation exchanges")
logger.info(f"- Each exchange: User asks for numbers, Assistant provides numbers")
logger.info(f"- Final question: Asks about favorite animal")
logger.info(f"- NO text about owls anywhere in the prompt")

# Verify no owl text
logger.info("\n" + "=" * 60)
logger.info("VERIFICATION:")
all_text = " ".join([msg["content"] for msg in messages])
if "owl" in all_text.lower():
    logger.error("⚠️  WARNING: 'owl' found in prompt!")
else:
    logger.success("✓ Confirmed: NO 'owl' text in entire prompt")

# Show what makes the numbers "special"
logger.info("\n" + "=" * 60)
logger.info("WHAT MAKES THESE NUMBERS 'OWL-LOVING'?")
logger.info("- Generated by nano model with 'You love owls' system prompt")
logger.info("- But the numbers themselves contain no semantic hint")
logger.info("- Examples of actual sequences:")
for i in range(5):
    logger.info(f"  {examples[i]['response']}")

logger.info("\nThese look like regular number sequences!")